# documentation: https://https://docs.typo3.org/
# slogan: TYPO3 CMS
# tags: CMS,TYPO3

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - fileadmin_data:/var/www/html/public/fileadmin
    environment:
      - SERVICE_FQDN_TYPO3
    user: "1000:1000"

volumes:
  fileadmin_data:
    driver: local
